# Generated by Django 3.0.7 on 2020-06-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200630_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='inputName',
        ),
    ]
